languageCode: "en-us"
contentdir: "content"
publishdir: "public"
builddrafts: false
baseurl: "https://andrewjesaitis.com"
canonifyurls: true
theme: "hot-chocolate"
title: "Andrew Jesaitis"
author: "Andrew Jesaitis"

PygmentsUseClasses: false
PygmentsCodeFences: true
PygmentsStyle: "default"
pluralizelisttitles: true

permalinks:
  post: /:year/:month/:title/
indexes:
   category: "categories"
params:
  AuthorName: "Andrew"
  cachebuster: false
  dateform: "Jan 2, 2006"
  dateformfull: "Mon Jan 2 2006 15:04:05 MST"
  gravatar: "andrew@andrewjesaitis.com"
  github: "https://github.com/andrewjesaitis"
  tumblr: "http://andrewjesaitis.tumblr.com"
  flickr: "https://flickr.com/andrewjesaitis"
  email: "andrew@andrewjesaitis.com"
  description: "Powered by coffee."  
  linkedin: "https://linkedin.com/in/andrewjesaitis"
