languageCode: "en-us"
contentdir: "content"
publishdir: "public"
builddrafts: false
baseurl: "http://andrewjesaitis.com"
canonifyurls: true
theme: "hugo-uno"
title: "Andrew Jesaitis"
author: "Andrew Jesaitis"

indexes:
   category: "categories"
   tag: "tags"
params:
  AuthorName: "Andrew"
  github: "andrewjesaitis"
  #bitbucket: "andrewjesaitis"
  tumblr: "andrewjesaitis"
  flickr: "andrewjesaitis"
  twitter: "andrewjesaitis"
  email: "andrew@andrewjesaitis.com"
  description: "Powered by coffee."
  about: "/pages/about"
  projects: "/categories/projects"
  #cv: "/pages/cv"
  linkedin: "andrewjesaitis"
  cover: "/images/background.jpg"
  logo: "/images/logo.jpg"
  google_analytics_id: "UA-40063106-1"